refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    target: stdout
    encoder:
      pattern: "{h({d(%H:%M:%S)} [{l}])} -- {m}{n}"

  logfile:
    kind: file
    path: "log/main.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] -- {m}{n}"

root:
  level: debug 
  appenders:
    - stdout
    - logfile

